### ISSUE TITLE
Reinmplement DisplayDataAddress as a c-like enum

### ISSUE THREAD

**Issue by nilscript** [jasonpeacock/ht16k33#17]
Currently the DisplayDataAddress is implemented as a bitflags struct when it does not need to. It does not need to implement bitwise operations.

It would make more sense as to implement it as an c-like enum. If implemented with num_enum traits we would also gain the ability to convert from primitive numbers back and fourth to DisplayDataAddress with methods `::TryFrom(..)` and syntax as `row as u8`.

**Comment by nilscript** [comment]
This ofcourse would break existing api as the method `row.bits()` no longer exists.

**Comment by jasonpeacock** [comment]
Thank you for the changes, I've commented on the PR. Yes, I believe that small break in the API is OK. It's easy enough for consumers to update their code to use the latest library version, and the additional flexibility and ease of use of the more natural `u8` usage.

**Comment by nilscript** [comment]
Oh I guess I did put it all into one pull request. I thought those changes would'nt show up there. 
Most changes are here: [link](https://github.com/sesar54/ht16k33/blob/master/src/types/display_data_address.rs)
And some (not all) are here: [link](https://github.com/sesar54/ht16k33/commit/1da9c5740e7eb21553ad61060cc9139312c12220#diff-d8174489b90a1a9d5d82b3cd30e8b6e5)

**Comment by sesar54** [comment]
It's worth considering to
